-- Skins table inserts
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3313035, 'Five-SeveN | Coolant', 'PIST', 706, 'FT', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (5513035, 'Nova | Mandrel', 'SHTG', 865, 'BS', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (33130351, 'P250 | Facility Draft', 'PIST', 785, 'FT', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4316918, 'MAC-10 | Bronzer', 'SMG', 783, 'FT', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (2335199, 'SCAR-20 | Fragments', 'SNPR', 773, 'FT', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4343951, 'MAC-10 | Allure', 'SMG', 736, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1236918, 'M4A4 | Choppa', 'RIFL', 9, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (2536918, 'StatTrak SSG 08 | Memorial', 'SNPR', 199, 'BS', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (6334428, 'M249 | O.S.I.P.R.', 'MCHG', 331, 'FT', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4343220, 'UMP-45 | Moonrise', 'SMG', 195, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3345199, 'R8 Revolver | Banana Cannon', 'PIST', 428, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3334722, 'Five-SeveN | Scrawl', 'PIST', 670, 'FT', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (5444726, 'XM1014 | Zombie Offensive', 'SHTG', 167, 'WW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1533955, 'StatTrak SG 553 | Ol'' Rusty', 'RIFL', 911, 'BS', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4213035, 'PP-Bizon | Facility Sketch', 'SMG', 459, 'MW', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (5343955, 'MAG-7 | Monster Call', 'SHTG', 370, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (6326918, 'Negev | Sour Grapes', 'MCHG', 968, 'FT', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1345199, 'M4A1-S | Emphorosaur-S', 'RIFL', 529, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (33451991, 'Glock-18 | Umbral Rabbit', 'PIST', 647, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (5223107, 'Nova | Candy Apple', 'SHTG', 891, 'MW', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4323107, 'MP9 | Orange Peel', 'SMG', 175, 'FT', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3326918, 'Dual Berettas | Rose Nacre', 'PIST', 452, 'FT', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (2355199, 'AWP | Duality', 'SNPR', 632, 'FT', 'CL', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3444428, 'Desert Eagle | Trigger Discipline', 'PIST', 145, 'WW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4434910, 'UMP-45 | Roadblock', 'SMG', 2, 'WW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4235721, 'MAC-10 | Light Box', 'SMG', 815, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3335199, 'StatTrak P250 | Re.built', 'PIST', 546, 'FT', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (42357211, 'UMP-45 | Motorized', 'SMG', 730, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4223107, 'PP-Bizon | Night Ops', 'SMG', 321, 'MW', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3356918, 'Glock-18 | Shinobu', 'PIST', 24, 'FT', 'CL', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (6236276, 'Souvenir M249 | Humidor', 'MCHG', 426, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (62362761, 'Souvenir M249 | Humidor', 'MCHG', 385, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4116276, 'Souvenir PP-Bizon | Anolis', 'SMG', 963, 'FN', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3555199, 'P2000 | Wicked Sick', 'PIST', 236, 'BS', 'CL', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1445721, 'M4A4 | Etch Lord', 'RIFL', 495, 'WW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4535199, 'StatTrak MP9 | Featherweight', 'SMG', 972, 'BS', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3233035, 'USP-S | Check Engine', 'PIST', 74, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (6333955, 'StatTrak Negev | Ultralight', 'MCHG', 396, 'FT', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (6344428, 'Negev | dev_texture', 'MCHG', 416, 'FT', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (5253955, 'XM1014 | Entombed', 'SHTG', 809, 'MW', 'CL', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4443955, 'MAC-10 | Allure', 'SMG', 494, 'WW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (2235721, 'SSG 08 | Dezastre', 'SNPR', 789, 'MW', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3245721, 'Glock-18 | Block-18', 'PIST', 983, 'MW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3334726, 'StatTrak P2000 | Lifted Spirits', 'PIST', 346, 'FT', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3344910, 'StatTrak R8 Revolver | Crazy 8', 'PIST', 449, 'FT', 'RS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4136918, 'MP9 | Nexus', 'SMG', 797, 'FN', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3213035, 'Five-SeveN | Coolant', 'PIST', 386, 'MW', 'CG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (44349101, 'StatTrak MAC-10 | Monkeyflage', 'SMG', 824, 'WW', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3323107, 'P2000 | Granite Marbleized', 'PIST', 73, 'FT', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4124694, 'UMP-45 | Carbon Fiber', 'SMG', 731, 'FN', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4323035, 'MAC-10 | Calf Skin', 'SMG', 604, 'FT', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1223035, 'Galil AR | Cold Fusion', 'RIFL', 630, 'MW', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4135199, 'MP9 | Featherweight', 'SMG', 858, 'FN', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3123107, 'P250 | Metallic DDPAT', 'PIST', 934, 'FN', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4535721, 'StatTrak UMP-45 | Motorized', 'SMG', 363, 'BS', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3244726, 'USP-S | Ticket to Hell', 'PIST', 113, 'MW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1243107, 'M4A1-S | Nitro', 'RIFL', 893, 'MW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (1244428, 'AK-47 | Slate', 'RIFL', 785, 'MW', 'RS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3423107, 'Dual Berettas | Stained', 'PIST', 983, 'WW', 'IG', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (4334726, 'StatTrak MAC-10 | Ensnared', 'SMG', 509, 'FT', 'MS', 1);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (3133107, 'Five-SeveN | Silver Quartz', 'PIST', 817, 'FN', 'MS', 0);
INSERT INTO Skins (SkinID, Skin_Name, ItemID, Pattern, FloatID, RarityID, StatTrak) VALUES (52231071, 'XM1014 | Blue Steel', 'SHTG', 2, 'MW', 'IG', 0);
